#!/bin/bash
export WATCHFILES_IGNORE_PATHS="./logs.log, ./invite_token"

sudo service docker start
sleep 1
source /etc/profile

CERT_PATH="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
KEY_PATH="/etc/letsencrypt/live/$DOMAIN/privkey.pem"

source ./venv/bin/activate
docker compose up -d

if [ -f "$CERT_PATH" ] && [ -f "$KEY_PATH" ]; then
    uvicorn backend.app.main:app --reload --loop uvloop --host 0.0.0.0 --port 8000 \
        --ssl-certfile=$CERT_PATH \
        --ssl-keyfile=$KEY_PATH \
        --log-config ./config/log.ini \
        --reload-dir backend
else
    uvicorn backend.app.main:app --reload --host 0.0.0.0 --port 80 --log-config ./config/log.ini
fi
